include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v3/common.yml'

.projecttest:
  extends: .test
  script:
    - apt-get update
    - apt-get install --yes --no-install-recommends cmake gfortran mpich libmpich-dev
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH
    - julia --project=$CI_JULIA_PROJECT -e '
                          using Pkg;
                          Pkg.instantiate();
                          Pkg.resolve();
                          Pkg.build();
                          include("test/runtests.jl");'
.gputest:
  extends: .projecttest
  variables:
    CI_IMAGE_TAG:     'cuda'
    CI_JULIA_PROJECT: 'env/gpu'
  tags:
    - cuda

.cputest:
  extends: .projecttest
  variables:
    CI_IMAGE_TAG:     'plain'
    CI_JULIA_PROJECT: '.'

gpu:test:dev:
  extends: .gputest
  variables:
    CI_VERSION_TAG: 'dev'

cpu:test:dev:
  extends: .cputest
  variables:
    CI_VERSION_TAG: 'dev'

gpu:test:v1.1:
  extends: .gputest
  variables:
    CI_VERSION_TAG: 'v1.1'

cpu:test:v1.1:
  extends: .cputest
  variables:
    CI_VERSION_TAG: 'v1.1'

# documentation:
#   extends: .documentation
#   dependencies:
#     - cpu:test:v1.1 
#   variables:
#     CI_VERSION_TAG: 'v1.1'
#     CI_IMAGE_TAG: 'plain'
#   only:
#     - master
#     - staging
#     - trying
# 
# pages:
#   dependencies:
#     - documentation
#   stage: deploy
#   script:
#     - mv docs/build public
#   artifacts:
#     paths:
#     - public
#   only:
#     - master

