## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
dist: trusty
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - staging
    - trying

addons:
  apt:
    packages:
      - gfortran
      - mpich
      - libmpich-dev

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew upgrade cmake
      brew cask uninstall oclint # Prevent conflict with gcc
      brew install mpich
    fi
  # Temporary fix for nightly build path
  - julia -e 'if VERSION >= v"1.2.0-DEV.42";
                 using Pkg;
                 Pkg.develop(PackageSpec(url="https://github.com/climate-machine/Canary.jl"));
               end'
  # - |
  #   if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #     curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
  #     source ./macports-ci install
  #     sudo port -N install mpich
  #   fi

before_install:
  - export CC=mpicc
  - export FC=mpif90

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("CLIMA")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.0
#       os: linux
#       script:
#         - export DOCUMENTER_DEBUG="true"
#         - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
#         - julia --color=yes --project=docs/ docs/make.jl
#       after_success: skip

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - export DOCUMENTER_DEBUG="true"
        - julia --color=yes --project=docs/ -e 'using Pkg;
                                                      Pkg.instantiate();
                                                      Pkg.develop(PackageSpec(path=pwd()));
                                                      Pkg.build("CLIMA")'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
