[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[ParametersType]]
path = "../../../ParametersType"
uuid = "046d00ba-03b1-11e9-3cca-b5213a01defd"
version = "0.0.0"

[[PlanetParameters]]
deps = ["ParametersType"]
path = "../../../PlanetParameters"
uuid = "50a4fe1a-031f-11e9-2493-0505e0da639e"
version = "0.0.0"
