[SlurmJob(`.slurmci/init.sh`) =>
 [SlurmJob(`.slurmci/cpu-test.sh`)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/Euler/isentropic_vortex_standalone.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_aux.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_source.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_bc.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/conservation/sphere.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/compressible_Navier_Stokes/mms_bc.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/compressible_Navier_Stokes/dycoms.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/compressible_Navier_Stokes/rtb_visc.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/sphere/advection_sphere_lsrk.jl`, ntasks=2)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/sphere/advection_sphere_ssp33.jl`, ntasks=2)
  SlurmJob(`.slurmci/cpu.sh test/DGmethods/sphere/advection_sphere_ssp34.jl`, ntasks=2)
  SlurmJob(`.slurmci/cpu.sh examples/DGmethods/ex_001_periodic_advection.jl`, ntasks=3)
  SlurmJob(`.slurmci/cpu.sh examples/DGmethods/ex_002_solid_body_rotation.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu-test.sh`)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/Euler/isentropic_vortex_standalone.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_aux.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_source.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/Euler/isentropic_vortex_standalone_bc.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/conservation/sphere.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/compressible_Navier_Stokes/mms_bc.jl`, ntasks=3)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/sphere/advection_sphere_lsrk.jl`, ntasks=2)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/sphere/advection_sphere_ssp33.jl`, ntasks=2)
  SlurmJob(`.slurmci/gpu.sh test/DGmethods/sphere/advection_sphere_ssp34.jl`, ntasks=2)
  ]
 ]
