function PlanetConstants{FT}(::Type{EarthParameters};
                             k_Karman =          FT(0.4),
                             molmass_dryair =    FT(28.97e-3),
                             R_d =               FT(gas_constant(FT)/molmass_dryair),
                             kappa_d =           FT(2//7),
                             cp_d =              FT(R_d/kappa_d),
                             cv_d =              FT(cp_d - R_d),
                             ρ_cloud_liq =       FT(1e3),
                             ρ_cloud_ice =       FT(916.7),
                             molmass_water =     FT(18.01528e-3),
                             molmass_ratio =     FT(molmass_dryair/molmass_water),
                             R_v =               FT(gas_constant(FT)/molmass_water),
                             cp_v =              FT(1859),
                             cp_l =              FT(4181),
                             cp_i =              FT(2100),
                             cv_v =              FT(cp_v - R_v),
                             cv_l =              FT(cp_l),
                             cv_i =              FT(cp_i),
                             T_freeze =          FT(273.15),
                             T_min =             FT(150.0),
                             T_max =             FT(1000.0),
                             T_icenuc =          FT(233.00),
                             T_triple =          FT(273.16),
                             T_0 =               FT(T_triple),
                             LH_v0 =             FT(2.5008e6),
                             LH_s0 =             FT(2.8344e6),
                             LH_f0 =             FT(LH_s0 - LH_v0),
                             e_int_v0 =          FT(LH_v0 - R_v*T_0),
                             e_int_i0 =          FT(LH_f0),
                             press_triple =      FT(611.657),
                             ρ_ocean =           FT(1.035e3),
                             cp_ocean =          FT(3989.25),
                             planet_radius =     FT(6.371e6),
                             day =               FT(86400),
                             Omega =             FT(7.2921159e-5),
                             grav =              FT(9.81),
                             year_anom =         FT(365.26*day),
                             orbit_semimaj =     FT(1*astro_unit(FT)),
                             TSI =               FT(1362),
                             MSLP =              FT(1.01325e5)
                             )
  return PlanetConstants{FT}(
                             k_Karman,
                             molmass_dryair,
                             R_d,
                             kappa_d,
                             cp_d,
                             cv_d,
                             ρ_cloud_liq,
                             ρ_cloud_ice,
                             molmass_water,
                             molmass_ratio,
                             R_v,
                             cp_v,
                             cp_l,
                             cp_i,
                             cv_v,
                             cv_l,
                             cv_i,
                             T_freeze,
                             T_min,
                             T_max,
                             T_icenuc,
                             T_triple,
                             T_0,
                             LH_v0,
                             LH_s0,
                             LH_f0,
                             e_int_v0,
                             e_int_i0,
                             press_triple,
                             ρ_ocean,
                             cp_ocean,
                             planet_radius,
                             day,
                             Omega,
                             grav,
                             year_anom,
                             orbit_semimaj,
                             TSI,
                             MSLP
                             )
end
